[package]
name = "jisi-code-migration"
version.workspace = true
edition.workspace = true

[lib]
name = "jisi_code_migration"
path = "src/lib.rs"

[dependencies]
sea-orm.workspace = true
sea-orm-migration.workspace = true
